CREATE TABLE EXECUTIVE_Dim
(
    EXECUTIVE_KEY VARCHAR2(100) primary key ,
    EXECUTIVE_NAME    VARCHAR2(500),
    EXECUTIVE_SINCE varchar2(10),
    EXECUTIVE_POSITION    VARCHAR2(200),
    EXECUTIVE_AGE    number(10),
    COMPANY_KEY    VARCHAR2(100)
);

INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_1', 'Seif Allah Coutry Saadi Hassan', '2008', 'Non-Executive Chairman', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_2', 'Ashraf Kamel Mousa Sabry', '2008', 'CEO, MD  Executive Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_3', 'Ashraf Mahmoud Abbas Zaki', '2015', 'Non-Executive Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_4', 'Babatunde Temitope Soyoye', '2022', 'Director', '53', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_5', 'Shehab Zidan', '2020', 'Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_6', 'Hedi ben Malouka', '2018', 'Non-Executive Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_7', 'Michael Fiebig', '2017', 'Non-Executive Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_8', 'Hussein Hassan Choukri', '2019', 'Independent Director', '71', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_9', 'Moataz Mohammed Hashim El Tabaa', '2019', 'Independent Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_10', 'Magda Raafat Habib', '2022', 'Independent Board Member', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_11', 'Aziz Moolji', '2022', 'Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_12', 'Sherif Safwat', '2022', 'Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('FWRY_13', 'Ahmed Al-Tanani', '2022', 'Director', '', 'FWRY');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('SWVL_1', 'Mr. Mostafa Kandil', '', 'Chairman  CEO', '30', 'SWVL');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('SWVL_2', 'Mr. Youssef Salem', '', 'Chief Financial Officer', '30', 'SWVL');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_1', 'Yasser Suleiman Hesham El Mallawany', '2000', 'Non-Executive Director', '61', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_2', 'Ahmed El-Wakil', '2021', 'Independent Non-Executive Chairman', '', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_3', 'Niels Thomsen', '2006', 'Group CEO  Director', '', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_4', 'Heba Safwan Thabet', '2006', 'Head of Business Development  Executive Director', '', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_5', 'Mariam Thabet', '2010', 'Non-Executive Director', '', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_6', 'Jan Anders Lindgren', '2021', 'Non-Executive Independent Director', '', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_7', 'Amr Fathi Mohammed Madany Salam', '', 'Executive Independent Director', '', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_8', 'Mesheal Al-Doghiem', '2021', 'Non-Executive Independent Director', '', 'JUFO');
INSERT INTO EXECUTIVE_Dim (EXECUTIVE_KEY , EXECUTIVE_NAME, EXECUTIVE_SINCE, EXECUTIVE_POSITION, EXECUTIVE_AGE, COMPANY_KEY) VALUES ('JUFO_9', 'Mahmoud Abd El-Wahab', '2021', 'Non-Executive Independent Director', '', 'JUFO');


